name: Backend CI

on:
  push:
    branches:
      - feature/actions
  pull_request:
    branches:
      - feature/actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables from GitHub Secrets
        run: |
          echo "BACKEND_API=${{ secrets.BACKEND_API }}" >> $GITHUB_ENV
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> $GITHUB_ENV
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> $GITHUB_ENV
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "GMAIL_PASS=${{ secrets.GMAIL_PASS }}" >> $GITHUB_ENV
          echo "GMAIL_USER=${{ secrets.GMAIL_USER }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
          echo "URL=${{ secrets.URL }}" >> $GITHUB_ENV

      - name: Set up Docker Compose with environment variables
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Install dependencies
        run: |
          docker compose exec backend npm install

      - name: Run tests
        run: |
          docker compose exec backend npm run test

      - name: Tear down Docker Compose
        run: |
          docker compose down
