name: Backend CI

on:
  push:
    branches:
      - feature/actions
  pull_request:
    branches:
      - feature/actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env file
        run: |
          cp .env .env

      - name: Set up Docker Compose with environment variables
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Install dependencies
        run: |
          docker-compose exec backend npm install

      - name: Run tests
        run: |
          docker-compose exec backend npm run test

      - name: Tear down Docker Compose
        run: |
          docker-compose down
